CREATE TABLE IF NOT EXISTS nft
(
    image_id VARCHAR(255) NOT NULL PRIMARY KEY UNIQUE,
    token_id VARCHAR(255) DEFAULT NULL UNIQUE,
    attributes VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    name VARCHAR(64) NOT NULL
);


